name: Build-Package-Deploy Workflow

on:
  push:
    branches:
      - main # Trigger build and package jobs on pushes to the main branch
  workflow_dispatch: # Allows manual trigger for deployment job

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Application
        run: |
          echo "Building the application..."
          # Add your build commands here

  package:
    name: Package Application
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Package Application
        run: |
          echo "Packaging the application..."
          # Add your packaging commands here

  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: package
    if: success() # Only proceed if terraform-plan job succeeds
    
    permissions:
      issues: write

    steps:
      - name: Await Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: naresh-egov # Replace with GitHub usernames, with the free version you can only have an issue assigned to one username
          minimum-approvals: 1
          issue-title: "Manual Approval Required for Deployment"
          issue-body: "Please approve or deny the deployment."
      - name: Approved
        run: |
          echo "Deploying the application..."
        
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: manual-approval
    if: ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          echo "Deploying the application..."
          # Add your deployment commands here      
